### ISSUE TITLE
Prepare Jenkins Pipelines for odh-alpinebits-server Project

### ISSUE THREAD

**Issue by RudiThoeni** [noi-techpark/odh-alpinebits-server#2]
- [x] CI
- [x] Deployment

**Comment by RudiThoeni** [comment]
A question about environment variables is open. Patrick & Peter are using application.properties to store environment variables. GappC used standard Environment Variables that can be set on tomcat launch. In our case that is not very useful.
After a discussion we agreed that GappC should switch also to application.properties. He can do this when he is back in Juny

**Comment by alexlanz** [comment]
Should be done!

**Comment by RudiThoeni** [comment]
Test Environment
alpinebits2.testingmachine.eu (at the moment)
Production Environment
alpinebits.opendatahub.bz.it
