### ISSUE TITLE
As a Open Data Hub PM I want to have online the AlpineBits Hotel Data Landing-page online in order to avoid misunderstanding due to the 405 error message.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/odh-alpinebits-server#54]
The goal of the issue is to publish the static Landingpage that explains how the AlpineBits Hotel Data request workflow is on the following link:
- https://alpinebits.opendatahub.bz.it/AlpineBits
- https://alpinebits.opendatahub.bz.it

**Comment by RudiThoeni** [comment]
The page Martin sent is this:

[dist.zip](https://github.com/noi-techpark/odh-alpinebits-server/files/5678522/dist.zip)

Since it contains "lorem ipsum" i asked him if this is the final version ;)

**Comment by Piiit** [comment]
@mrabans I've send you an email, but I will in the meantime test the redirects on testingmachine.eu and move the zip file into a dedicated repository.

**Comment by Piiit** [comment]
@mrabans @sseppi Done for testingmachine....
See https://alpinebits.opendatahub.testingmachine.eu and https://alpinebits.opendatahub.testingmachine.eu/AlpineBits 

All other paths give an error

**Comment by Piiit** [comment]
Apache2 rewrite rules for reference:
```sh
$ cat alpinebits.opendatahub.testingmachine.eu-le-ssl.conf 

<IfModule mod_ssl.c>
<VirtualHost *:443>
  <Proxy *>
    Order Allow,Deny
    Allow from all
  </Proxy>
  ServerName alpinebits.opendatahub.testingmachine.eu 
  SSLProxyEngine On
  RewriteEngine On
  ProxyPass / http://alpinebits-server.tomcat02.testingmachine.eu:8080/ Keepalive=On
  ProxyPassReverse / http://alpinebits-server.tomcat02.testingmachine.eu:8080/
  ErrorLog /var/log/apache2/eu.testingmachine.opendatahub.alpinebits

  RewriteCond %{REQUEST_METHOD}  =GET
  RewriteRule    "/AlpineBits$"  http://alpinebits.lp-test.s3-website-eu-west-1.amazonaws.com [P,END]
  RewriteCond %{REQUEST_METHOD}  =GET
  RewriteRule    ^  http://alpinebits.lp-test.s3-website-eu-west-1.amazonaws.com%{REQUEST_URI} [P]


SSLCertificateFile /etc/letsencrypt/live/alpinebits.opendatahub.testingmachine.eu/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/alpinebits.opendatahub.testingmachine.eu/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
```

**Comment by Piiit** [comment]
@mrabans @sseppi  Please test...

**Comment by mrabans** [comment]
@Piiit @sseppi works great! See https://github.com/noi-techpark/it.bz.opendatahub.alpinebits.landingpage/pull/1 for the text

**Comment by RudiThoeni** [comment]
works!
Martin added the text 
https://alpinebits.opendatahub.testingmachine.eu/

**Comment by Piiit** [comment]
@mrabans @sseppi @RudiThoeni Done... please check the production endpoint

**Comment by RudiThoeni** [comment]
checked, all online ;)
