### ISSUE TITLE
Migrate the odh alpinebits server to our docker environment

### ISSUE THREAD

**Issue by RudiThoeni** [noi-techpark/odh-alpinebits-server#63]
Migrate to docker and use github actions
https://github.com/noi-techpark/odh-alpinebits-server

migrate also this one pager https://github.com/noi-techpark/it.bz.opendatahub.alpinebits.landingpage

**Comment by RudiThoeni** [comment]
The Alpinebits Library for Maven Central Repository is also part of this migration to Github Actions
https://github.com/noi-techpark/odh-alpinebits

**Comment by RudiThoeni** [comment]
In the meantime i got a request to deploy a new alpinebits server library / server
on deploying the alpinebits lib to the maven central repo jenkins showed 
`[INFO] --- maven-gpg-plugin:1.6:sign (sign-artifacts) @ alpinebits-root ---
gpg: no default secret key: No secret key
gpg: signing failed: No secret key`

(https://jenkins.testingmachine.eu/job/it.bz.opendatahub.alpinebits/job/libraries.release/54/consoleFull)

I saw the file odh-ossrh-gpg-key is present in jenkins.... and nothing was modified, have you any hint on what the reason is and how it can be fixed? (maybe some plugin/library changed?)

**Comment by alexlanz** [comment]
Can this be closed now?

**Comment by RudiThoeni** [comment]
No the migration to docker/github actions still has to be done for the repos

https://github.com/noi-techpark/odh-alpinebits-server
https://github.com/noi-techpark/odh-alpinebits

**Comment by gappc** [comment]
HI  @RudiThoeni, @alexlanz

I've implemented the switch to Spring and GitHub actions, please take a look at PR https://github.com/noi-techpark/odh-alpinebits-server/pull/70.

I used the Innovation ScoreBoard (https://github.com/noi-techpark/davinci-innovation-scoreboard-api) as template. The "test" job looks fine (tests execute without error), but I cannot guarantee that the deployment jobs work - I couldn't test them.

Please take a look at the PR and let me know if / what has to be done.

**Please also note that the https://github.com/noi-techpark/odh-alpinebits project was not switched to GitHub actions yet**. I'm not sure if I should prepare a PR or if you do that.

**Comment by alexlanz** [comment]
Hi @gappc,

it looks good to me, great job. My suggestion is to merge it and test the deployment. Then we see if we forgot something. If so, we can also change it on the go.

**Comment by RudiThoeni** [comment]
prod and main are deployed and online, for the alpinebits library i will create another issue
